// SERIAL PIN CONFIGURATION //

#define ESP_RX PA1
#define ESP_TX PA4
#define ESP_BAUDRATE 4800

// SENSOR PIN CONFIGURATION //

#define DHT_PIN PA0_ALT1
#define MQ_PIN PA1  
#define LDR_PIN PC1

// ACTUATOR PIN CONFIGURATION //
#define BUZZER_PIN PA0
#define MOTOR_PIN_IN1 PA4
#define MOTOR_PIN_IN2 PB0
#define MOTOR_PWM PB3

#define LED_PIN PB5