// SERIAL PIN CONFIGURATION //

#define ESP_RX PA1
#define ESP_TX PA4

// SENSOR PIN CONFIGURATION //

#define DHT_PIN PA0_ALT1
#define MQ_PIN PA1  
#define LDR_PIN PC1

// ACTUATOR PIN CONFIGURATION //
#define BUZZER_PIN PA0